function out = initialize_out_struct(n)

out(n) = struct(...
    'rate',[],...
    'cos',[],...
    'un_cos',[],...
    'change',[],...
    'unchanged_labels',[],...
    'added_labels',[],...
    'dist',[],...
    'unchanged_locs',[],...
    'added_locs',[],...
    'change_block',[],...
    'findices',[],...
    'bindices',[],...
    'fs',[],...
    'block_dur',[],...
    'run_dur',[],...
    'cosi',[],...
    'metrics',[],...
    'ad',[],...
    'unchanged_anatomy',[],...
    'added_anatomy',[]);
    

end